// fish_predatory.js

// Переменная экспорта для хищных и редких видов рыб (23 вида)
const fishDataPredatory = [
    { id: 'pike', name: 'Щука', category: 'Хищные', habitat: 'Озера, реки', diet: 'Рыба', size: '50-100 см', seasons: ['spring', 'autumn'], description: 'Крупная пресноводная хищная рыба, известная своим агрессивным клевом.', tips: 'Ловля на воблеры, блесны-колебалки и джеркбейты.', regulations: 'Минимальный размер 32 см. Строгий нерестовый запрет весной.', image_url: 'shchuka.png' }, // ⭐ Добавлено
    { id: 'perch', name: 'Окунь', category: 'Хищные', habitat: 'Вездесущ', diet: 'Мелкая рыба', size: '15-40 см', seasons: ['all'], description: 'Самая распространенная хищная рыба, охотится стаями.', tips: 'Эффективен джиг, отводной поводок, мелкие вертушки.', regulations: 'Любительский лов разрешен, но соблюдайте лимиты.', image_url: 'okun.png' }, // ⭐ Добавлено
    { id: 'sudak', name: 'Судак', category: 'Хищные', habitat: 'Чистые, глубокие', diet: 'Мелкая рыба', size: '40-80 см', seasons: ['summer', 'autumn'], description: 'Ценная рыба с диетическим мясом. Предпочитает песчаное или каменистое дно.', tips: 'Лучшая снасть — джиг, особенно на закате и ночью.', regulations: 'Минимальный размер 40 см. Нерестовый запрет.', image_url: 'sudak.png' }, // ⭐ Добавлено
    { id: 'som', name: 'Сом', category: 'Хищные', habitat: 'Ямы и омуты', diet: 'Рыба, раки', size: '100-300+ см', seasons: ['summer'], description: 'Самый крупный пресноводный хищник России. Ведет ночной образ жизни.', tips: 'Ловят на квок, крупного живца или мясо.', regulations: 'Лов ограничен, особенно крупных особей.', image_url: 'som.png' }, // ⭐ Добавлено
    { id: 'trout', name: 'Форель', category: 'Хищные', habitat: 'Горные ручьи', diet: 'Насекомые', size: '20-50 см', seasons: ['spring', 'summer', 'autumn'], description: 'Индикатор чистоты воды. Бывает озерная и ручьевая.', tips: 'Ловля нахлыстом на сухую мушку или мелкие блесны.', regulations: 'Ловля строго по лицензии или в форелевых хозяйствах.', image_url: 'forel.png' }, // ⭐ Добавлено
    { id: 'zander', name: 'Берш', category: 'Хищные', habitat: 'Водохранилища', diet: 'Мелкая рыба', size: '25-45 см', seasons: ['autumn'], description: 'Близкий родственник судака, но не вырастает таким крупным.', tips: 'Джиг у дна, мелкие приманки.', regulations: 'Ограничения.', image_url: 'bersh.png' }, // ⭐ Добавлено
    { id: 'asp', name: 'Жерех', category: 'Хищные', habitat: 'Поверхность рек', diet: 'Мелкая рыба', size: '40-60 см', seasons: ['summer'], description: 'Поверхностный хищник. Охотится "боем" на течении.', tips: 'Ловля на кастмастер или поверхностные приманки.', regulations: 'Ограничения.', image_url: 'zherekh.png' }, // ⭐ Добавлено
    { id: 'grayling', name: 'Хариус', category: 'Хищные', habitat: 'Горные реки', diet: 'Насекомые', size: '25-40 см', seasons: ['summer'], description: 'Рыба холодных вод, отличается крупным, ярким спинным плавником.', tips: 'Ловля на мушку или мелкие, чистые блесны.', regulations: 'Строгие ограничения, лицензионный лов.', image_url: 'kharius.png' }, // ⭐ Добавлено
    { id: 'salmon_atlantic', name: 'Семга', category: 'Хищные', habitat: 'Северные реки', diet: 'Рыба', size: '50-150 см', seasons: ['summer'], description: 'Царская рыба. Проходной лосось, идущий на нерест.', tips: 'Нахлыст, спиннинг с крупными приманками.', regulations: 'Строжайший контроль, лов только по именным лицензиям.', image_url: 'semga.png' }, // ⭐ Добавлено
    { id: 'eel', name: 'Угорь', category: 'Хищные', habitat: 'Озера, реки', diet: 'Мелкая рыба', size: '50-100 см', seasons: ['autumn'], description: 'Змеевидная рыба. Долгожитель. Охотится ночью.', tips: 'Ночная ловля на живца или червя.', regulations: 'Редкий вид, лов часто запрещен или строго ограничен.', image_url: 'ugor.png' }, // ⭐ Добавлено
    { id: 'catfish_wels', name: 'Налим', category: 'Хищные', habitat: 'Холодные реки', diet: 'Рыба', size: '30-60 см', seasons: ['winter'], description: 'Единственный представитель тресковых в пресных водах. Активен зимой.', tips: 'Ловля зимой на донные снасти на живца.', regulations: 'Зимний запрет в нерестовый период.', image_url: 'nalim.png' }, // ⭐ Добавлено
    { id: 'sturgeon_russian', name: 'Осетр', category: 'Редкие', habitat: 'Крупные реки', diet: 'Моллюски', size: '100-200 см', seasons: ['all'], description: 'Древнейшая рыба. Ценный, исчезающий вид.', tips: 'Ловля запрещена.', regulations: 'Полный запрет на любительский лов.', image_url: 'osetr.png' }, // ⭐ Добавлено
    { id: 'chum_salmon', name: 'Кета', category: 'Хищные', habitat: 'Тихий океан', diet: 'Рыба', size: '60-90 см', seasons: ['summer'], description: 'Дальневосточный лосось. Идет на нерест в реки.', tips: 'Спиннинг с крупными яркими блеснами.', regulations: 'Промысловый лов строго лимитирован.', image_url: 'keta.png' }, // ⭐ Добавлено
    { id: 'pink_salmon', name: 'Горбуша', category: 'Хищные', habitat: 'Тихий океан', diet: 'Рыба', size: '30-50 см', seasons: ['summer'], description: 'Самый маленький лосось. Сильно меняет внешний вид перед нерестом.', tips: 'Спиннинг.', regulations: 'Промысловый лов строго лимитирован.', image_url: 'gorbusha.png' }, // ⭐ Добавлено
    { id: 'tuna', name: 'Тунец (Южный)', category: 'Хищные', habitat: 'Черное море', diet: 'Мелкая рыба', size: '50-150 см', seasons: ['summer'], description: 'Быстрый пелагический хищник, мигрирующий в Черное море.', tips: 'Троллинг с искусственными приманками.', regulations: 'Редкий трофей.', image_url: 'tunec.png' }, // ⭐ Добавлено
    { id: 'bluegill', name: 'Солнечный окунь', category: 'Хищные', habitat: 'Южные пруды', diet: 'Черви', size: '10-15 см', seasons: ['summer'], description: 'Агрессивный, инвазивный вид из Северной Америки.', tips: 'Ловля на опарыша, мелкие блесны.', regulations: 'Ограничен, часто не желателен.', image_url: 'solnechny-okun.png' }, // ⭐ Добавлено
    { id: 'turbot', name: 'Тюрбо', category: 'Хищные', habitat: 'Черное море', diet: 'Рыба', size: '30-70 см', seasons: ['summer'], description: 'Ценная морская камбала. Отлично маскируется на дне.', tips: 'Донное удилище с приманкой на дне (например, креветка).', regulations: 'Промысловый лов.', image_url: 'tyurbo.png' }, // ⭐ Добавлено
    { id: 'catfish_european', name: 'Сом (европейский)', category: 'Хищные', habitat: 'Крупные реки', diet: 'Рыба', size: '150-300 см', seasons: ['summer'], description: 'Гигант пресных вод Европы и России. Может достигать огромных размеров.', tips: 'Квок, живец, крупные силиконовые приманки.', regulations: 'Ограничения, обязателен отпуск крупных особей.', image_url: 'som-evropeyskiy.png' }, // ⭐ Добавлено
    { id: 'sterlet', name: 'Стерлядь', category: 'Редкие', habitat: 'Крупные реки', diet: 'Донные организмы', size: '30-50 см', seasons: ['all'], description: 'Ценный осетровый вид. Объект разведения.', tips: 'Ловля запрещена.', regulations: 'Полный запрет на любительский лов.', image_url: 'sterlyad.png' }, // ⭐ Добавлено
    { id: 'nelma', name: 'Нельма', category: 'Хищные', habitat: 'Северные реки', diet: 'Рыба', size: '60-130 см', seasons: ['autumn'], description: 'Сибирский лосось, нерестится в реках.', tips: 'Спиннинг, крупные колеблющиеся блесны.', regulations: 'Лицензионный лов, строгие правила.', image_url: 'nelma.png' }, // ⭐ Добавлено
    { id: 'taimen', name: 'Таймень', category: 'Хищные', habitat: 'Сибирские реки', diet: 'Рыба', size: '80-150 см', seasons: ['summer'], description: 'Крупнейший лосось в мире. Редкий и ценный трофей.', tips: 'Крупные воблеры, мыши, нахлыст.', regulations: 'Полный запрет на ловлю, только "поймал-отпусти".', image_url: 'taymen.png' }, // ⭐ Добавлено
    { id: 'charr', name: 'Голец', category: 'Хищные', habitat: 'Высокогорные озера', diet: 'Насекомые', size: '20-40 см', seasons: ['summer'], description: 'Рыба ледниковых озер. Мясо красного цвета.', tips: 'Ловля на мушку или мелкие, чистые блесны.', regulations: 'Лицензионный лов.', image_url: 'golets.png' }, // ⭐ Добавлено
    { id: 'bullhead', name: 'Ротан', category: 'Хищные', habitat: 'Зарастающие пруды', diet: 'Мелкая рыба', size: '10-25 см', seasons: ['all'], description: 'Ненасытный инвазивный хищник. Выживает даже при полном промерзании водоема.', tips: 'Ловля на червя, маленького живца, мормышку.', regulations: 'Без ограничений, часто рекомендуется отлов.', image_url: 'rotan.png' } // ⭐ Добавлено
];
